package com.emmanuela.launcher.ui.components

import com.emmanuela.launcher.R


import android.content.res.Configuration
import androidx.compose.runtime.*
import androidx.compose.ui.platform.LocalContext
import java.util.Locale

val LocalLauncherLanguage=staticCompositionLocalOf{"system"}
private val translatedLabels=mapOf(
    "Search the web" to R.string.search_web,
    "SETTINGS" to R.string.ui_0,
    "General" to R.string.ui_1,
    "Your space" to R.string.ui_2,
    "System" to R.string.ui_3,
    "About" to R.string.ui_4,
    "Home screen" to R.string.ui_5,
    "App list" to R.string.ui_6,
    "App List" to R.string.ui_6,
    "Folders" to R.string.ui_7,
    "Appearance" to R.string.ui_8,
    "Gestures" to R.string.ui_9,
    "Apps" to R.string.ui_10,
    "Mindful Use" to R.string.ui_11,
    "Live the Moment" to R.string.ui_12,
    "Private Space" to R.string.ui_13,
    "App settings" to R.string.ui_14,
    "Aliases & tags" to R.string.ui_15,
    "Folder assignments" to R.string.ui_16,
    "Notifications" to R.string.ui_17,
    "Hidden apps" to R.string.ui_18,
    "Blocked apps" to R.string.ui_19,
    "Private apps" to R.string.ui_20,
    "Security" to R.string.ui_21,
    "Default launcher" to R.string.ui_22,
    "Language" to R.string.ui_23,
    "Permissions" to R.string.ui_24,
    "Battery optimization" to R.string.ui_25,
    "Backup & restore" to R.string.ui_26,
    "Favorites" to R.string.ui_27,
    "Alignment" to R.string.ui_28,
    "Spacing" to R.string.ui_29,
    "Widgets" to R.string.ui_30,
    "Manage widgets" to R.string.ui_31,
    "Arrange widgets" to R.string.ui_32,
    "Bottom controls" to R.string.ui_33,
    "Show status bar" to R.string.ui_34,
    "Enabled" to R.string.ui_35,
    "Font" to R.string.ui_36,
    "Color" to R.string.ui_37,
    "Background" to R.string.ui_38,
    "Size" to R.string.ui_39,
    "Position" to R.string.ui_40,
    "Style" to R.string.ui_41,
    "Clock" to R.string.ui_42,
    "Date" to R.string.ui_43,
    "Weather" to R.string.ui_44,
    "Screen time" to R.string.ui_45,
    "Battery" to R.string.ui_46,
    "Location" to R.string.ui_47,
    "Save" to R.string.ui_48,
    "Cancel" to R.string.ui_49,
    "Reset" to R.string.ui_50,
    "Apply" to R.string.ui_51,
    "Search apps" to R.string.ui_52,
    "All Apps" to R.string.ui_53,
    "Organized Folders" to R.string.ui_54,
    "Home" to R.string.ui_55,
    "Settings" to R.string.ui_56,
    "Motion" to R.string.ui_57,
    "Daily wallpaper" to R.string.ui_58,
    "Choose wallpaper" to R.string.ui_59,
    "Adjust wallpaper" to R.string.ui_60,
    "Privacy policy" to R.string.ui_61,
    "FAQs" to R.string.ui_62,
    "Photo directory" to R.string.ui_63,
    "Take a moment" to R.string.ui_64,
    "Open app" to R.string.ui_65,
    "Standard settings" to R.string.ui_66,
    "Advanced settings" to R.string.ui_67,
    "Layout" to R.string.v23_0,
    "Search" to R.string.v23_1,
    "Alphabet" to R.string.v23_2,
    "Colors" to R.string.v23_3,
    "Typography" to R.string.v23_4,
    "Wallpaper" to R.string.v23_5,
    "Behavior" to R.string.v23_6,
    "Groups" to R.string.v23_7,
    "Usage" to R.string.v23_8,
    "Schedule" to R.string.v23_9,
    "Strict mode" to R.string.v23_10,
    "Mindful prompt" to R.string.v23_11,
    "Daily limit" to R.string.v23_12,
    "Session limit" to R.string.v23_13,
    "Pause before opening" to R.string.v23_14,
    "Increase after repeated opens" to R.string.v23_15,
    "Require authentication" to R.string.v23_16,
    "Authentication" to R.string.v23_17,
    "Auto lock" to R.string.v23_18,
    "Search style" to R.string.v23_19,
    "Cursor style" to R.string.v23_20,
    "Text size" to R.string.v23_21,
    "Text style" to R.string.v23_22,
    "Widget style" to R.string.v23_23,
    "Text color" to R.string.v23_24,
    "Accent color" to R.string.v23_25,
    "Background color" to R.string.v23_26,
    "Reset custom colors" to R.string.v23_27,
    "Custom font" to R.string.v23_28,
    "Transparency" to R.string.v23_29,
    "Italic" to R.string.v23_30,
    "Weight" to R.string.v23_31,
    "Dim" to R.string.v23_32,
    "Blur" to R.string.v23_33,
    "Animations" to R.string.v23_34,
    "Animation" to R.string.v23_35,
    "Animation speed" to R.string.v23_36,
    "Speed" to R.string.v23_37,
    "Reduce motion" to R.string.v23_38,
    "Show alphabet" to R.string.v23_39,
    "Show alphabet on Home" to R.string.v23_40,
    "Home alphabet" to R.string.v23_41,
    "Haptics" to R.string.v23_42,
    "Hide from search" to R.string.v23_43,
    "Hide private apps from search" to R.string.v23_44,
    "App icons" to R.string.v23_45,
    "Show app icons" to R.string.v23_46,
    "Background fill" to R.string.v23_47,
    "Close after launch" to R.string.v23_48,
    "Folder animation" to R.string.v23_49,
    "Locked folders" to R.string.v23_50,
    "Lock folder" to R.string.v23_51,
    "Sort apps" to R.string.v23_52,
    "Layout style" to R.string.v23_53,
    "Select folders" to R.string.v23_55,
    "+ Add tag" to R.string.v23_56,
    "Add tag" to R.string.v23_57,
    "Add" to R.string.v23_58,
    "+ Add apps" to R.string.v23_59,
    "Back" to R.string.v23_60,
    "Done" to R.string.v23_61,
    "Hidden" to R.string.v23_62,
    "Blocked" to R.string.v23_63,
    "Private" to R.string.v23_64,
    "Daily new wallpaper" to R.string.v23_65,
    "Daily goal" to R.string.v23_66,
    "Most used" to R.string.v23_67,
    "Today" to R.string.v23_68,
    "Open Digital Wellbeing" to R.string.v23_69,
    "Allow notifications" to R.string.v23_70,
    "Advanced options enabled" to R.string.v23_71,
    "Advanced options disabled" to R.string.v23_72,
    "Choose action" to R.string.v23_73,
    "Launcher" to R.string.v23_74,
    "Other" to R.string.v23_75,
    "None" to R.string.v23_76,
    "Quick guide / FAQs" to R.string.v23_77,
    "Follow system language" to R.string.v23_78,
    "Reset app rules" to R.string.v23_79,
    "System app info" to R.string.v23_81,
    "Regular" to R.string.v23_82,
    "Medium" to R.string.v23_83,
    "Bold" to R.string.v23_84,
    "Small" to R.string.v23_85,
    "Large" to R.string.v23_86,
    "Fast" to R.string.v23_87,
    "Normal" to R.string.v23_88,
    "Slow" to R.string.v23_89,
    "Off" to R.string.v23_90,
    "Left" to R.string.v23_91,
    "Right" to R.string.v23_92,
    "Center" to R.string.v23_93,
    "Top" to R.string.v23_94,
    "Bottom" to R.string.v23_95,
    "Text" to R.string.v23_96,
    "Icons" to R.string.v23_97,
    "Grid" to R.string.v23_98,
    "List" to R.string.v23_99,
    "Freeform" to R.string.v23_100,
    "Minimal" to R.string.v23_101,
    "Compact" to R.string.v23_102,
    "Biometric + device credential" to R.string.v23_103,
    "Device credential" to R.string.v23_104,
    "Immediately" to R.string.v23_105,
    "30 seconds" to R.string.v23_106,
    "Screen off" to R.string.v23_107,
    "Enable Home" to R.string.v24_0,
    "Home text style" to R.string.v24_1,
    "Use custom Home text style" to R.string.v24_2,
    "Inherit" to R.string.v24_3,
    "Background opacity" to R.string.v24_4,
    "Rounded corners" to R.string.v24_5,
    "Home alphabet and App List can be enabled independently." to R.string.v24_6,
    "Wave movement" to R.string.v24_7,
    "Contact search (@)" to R.string.v24_8,
    "Search contacts with @" to R.string.v24_9,
    "Contacts permission" to R.string.v24_10,
    "Contacts" to R.string.v24_11,
    "Phone contacts are included by default. Other apps appear only when they expose contact integrations to Android." to R.string.v24_12,
    "Search apps, #tag or @contact" to R.string.v24_13,
    "Allow contacts access to search names with @." to R.string.v24_14,
    "Allow contacts" to R.string.v24_15,
    "Open app permissions" to R.string.v24_16,
    "Type a contact name after @" to R.string.v24_17,
    "No contacts found" to R.string.v24_18,
    "Digital Wellbeing destination" to R.string.v24_19,
    "Use automatic destination" to R.string.v24_20,
    "Search Android settings" to R.string.v24_21,
    "Test shortcut" to R.string.v24_22,
    "Weather website" to R.string.v24_23,
    "Use website on tap" to R.string.v24_24,
    "Wallpaper preview" to R.string.v24_25,
    "This folder's size" to R.string.v24_26,
    "Width fits within this folder's column. Other folders retain their own sizes." to R.string.v24_27,
    "Reset this folder's size" to R.string.v24_28,
    "Minimal. Personal. Yours." to R.string.v24_29,
    "Flashlight / camera" to R.string.v24_30,
    "Granted" to R.string.v24_31,
    "Not granted" to R.string.v24_32,
    "Widget options" to R.string.v25_0,
    "Show controls" to R.string.v25_1,
    "Hide controls" to R.string.v25_2,
    "Photo" to R.string.v25_3,
    "Share the app" to R.string.v25_4,
    "Manage apps" to R.string.v25_5,
    "Manage private apps" to R.string.v25_6,
    "No private apps" to R.string.v25_7,
    "Arrange apps" to R.string.v25_8,
    "Hold and drag to snap apps into place" to R.string.v25_9,
    "Keep custom app order" to R.string.v25_10,
    "Home uses its own text style" to R.string.v25_11,
    "On" to R.string.v25_12
)
@Composable
fun localized(value:String):String {
    val context=LocalContext.current
    val language=LocalLauncherLanguage.current
    val configuration=androidx.compose.ui.platform.LocalConfiguration.current
    val resources=remember(context,language,configuration){context.createConfigurationContext(Configuration(configuration).apply{if(language!="system")setLocale(Locale.forLanguageTag(language))}).resources}
    return translatedLabels[value]?.let{resources.getString(it)}?:value
}
